version: "3.7"

services:
  oms-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oms-client
    ports:
      - "1883:1883"
    volumes:
      - ./videos:/home/videos
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./run.sh:/home/run.sh
    command: ./run.sh
    network_mode: host
