from enum import Enum


class Topic(str, Enum):
    NODE_STATE = 'NODE_STATE'
    PLAY_VIDEO = 'PLAY_VIDEO'
    DISPLAY_URL = 'DISPLAY_URL'
    PLAY_PLAYLIST = 'PLAY_PLAYLIST'
    STOP_MEDIA = 'STOP_MEDIA'
    SET_SCHEDULE = 'SET_SCHEDULE'
    REQUEST_SCHEDULE = 'REQUEST_SCHEDULE'
    SET_DEFAULT_VIDEO = 'SET_DEFAULT_VIDEO'
    REQUEST_DEFAULT_VIDEO = 'REQUEST_DEFAULT_VIDEO'
    PLAYLIST_PLAYBACK = 'PLAYLIST_PLAYBACK'
    PLAYLIST_PLAYBACK_VIDEO = 'PLAYLIST_PLAYBACK_VIDEO'
    VIDEO_PLAYBACK = 'VIDEO_PLAYBACK'
    UPDATE_ACTIVE_SCHEDULE_ITEM = 'UPDATE_ACTIVE_SCHEDULE_ITEM'
    UPDATE_NODE = 'UPDATE_NODE'
    RESTART_NODE = 'RESTART_NODE'

    def __str__(self) -> str:
        return self.value
